### ISSUE TITLE
Include user who made change  (assuming a system where every user also has a postgres role)

### ISSUE THREAD

**Issue by reisepass** [supabase/supa_audit#48] opened 2022-12-30 18:36 UTC
# Feature request

A bit part of auditing for the use case I am working on is knowing who made a change. We already have nice tight integration between people using the software and postgres roles so we can use those roles for RBAC. It would be super elegant if we could also log these in an audit table without adding API level code everywhere.

**Comment by olirice** [comment] 2022-12-31 14:10
If you install supa_audit on the supabase platform (hosted or local) this feature is available. Check out the refs below.

I'm going to close this but feel free to re-open if that didn't answer your question

Refs:
dupe of #25 
feature added in #11

**Closed by olirice** 2022-12-31 14:10 UTC
Labels: enhancement
