### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by chrislaurie-io** [supabase/supa_audit#62] opened 2024-06-08 06:14 UTC
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I run the script (copy, paste run) on my Supabase I get this error:

ERROR:  0A000: pg_extension_config_dump() can only be called from an SQL script executed by CREATE EXTENSION

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Copy and paste script in new Supabase project.

## System information

- OS: macOS
- Browser Chrome 125
- Version of supabase-js: hosted version
- Version of Node.js: No idea

**Comment by olirice** [comment] 2024-06-10 15:19
dupe of https://github.com/supabase/supa_audit/issues/61
there are instructions on how to resolve in that issue

**Closed as completed by olirice** 2024-06-10 15:19 UTC
Labels: bug
