### ISSUE TITLE
running 0.3.1 standalone SQL file throws error

### ISSUE THREAD

**Issue by HyShai** [supabase/supa_audit#56] opened 2023-06-19 17:21 UTC
When running the standalone SQL file (in Supabase), the [newly added lines](https://github.com/supabase/supa_audit/commit/6c12c77774cf28119fcbf21ee5179dcb593a70a1) throw `pg_extension_config_dump can only be called from an SQL script executed by CREATE EXTENSION`.

**Comment by olirice** [comment] 2023-06-19 17:41
dupe of #55

**Closed by olirice** 2023-06-19 17:41 UTC
Labels: bug
