### ISSUE TITLE
Why I am getting this error on insert - record "old" is not assigned yet ?

### ISSUE THREAD

**Issue by vishalsodani** [supabase/supa_audit#65] opened 2024-08-15 01:48 UTC
I have enabled audit tracking for a table The update tracking works fine. But, when a new record is inserted I get the error shared below - 

``` DETAIL:  The tuple structure of a not-yet-assigned record is indeterminate. CONTEXT:  PL/pgSQL function audit.insert_update_delete_trigger() line 10 during statement block local variable initialization```

I have a Django web application with Postgres 14. I installed the extension by cloning the repo and running make install. 

I get this error when I add a new record for a model from the admin dashboard. The record is saved but this error is displayed on the webpage of the dashboard. I am attaching the screenshot of the error.

![supa_audit_error](https://github.com/user-attachments/assets/e487bd07-2053-4e70-a6f0-e17403a45396)

**Comment by olirice** [comment] 2024-08-15 14:55
This error is most frequently associated with triggers. Do you have other triggers on the same table being audited?

If you can you provide a minimal reproducible example I'd be happy to help resolve

**Comment by vishalsodani** [comment] 2024-08-16 07:33
Sorry, it appears that the plugin is designed to work with PostgreSQL 12 and later versions. Could you please confirm if this is correct? 

I was testing on PostgreSQL 10. It worked on PostgreSQL 12.

**Comment by olirice** [comment] 2024-08-16 15:00
ah yes, thats correct, we support 12+
Postgres 11 and below have been [EOL](https://www.postgresql.org/support/versioning/)d

Since you've got it working on 12 i'll close this issue but feel free to follow up if you have any questions

**Closed as completed by olirice** 2024-08-16 15:00 UTC
Labels: bug
